### PR TITLE
Add overlay and storage files for MOC

### PR DESCRIPTION
**Pull request by lmzuccarelli**
Updates to deploy storage specifics (pv, pvc and storerageclass objects) for the OKD-MOC  cluster

### CODE REVIEW

**Comment by aguidirh** [comment]
Verified 4.14 is working fine:

```
Name:              okd-coreos-build-4.14-pipelinerun-k54sq
Namespace:         okd-team
Pipeline Ref:      okd-coreos-build
Service Account:   pipeline
Labels:
 tekton.dev/pipeline=okd-coreos-build
Annotations:
 chains.tekton.dev/signed=true
 operator.tekton.dev/prune.keep=1
 operator.tekton.dev/prune.resources=taskrun, pipelinerun
 operator.tekton.dev/prune.skip=false
 operator.tekton.dev/prune.strategy=keep

🌡️  Status

STARTED          DURATION   STATUS
25 minutes ago   23m57s     Succeeded

⏱  Timeouts
 Pipeline:   4h0m0s

⚓ Params

 NAME                                VALUE
 ∙ environment                       operate-first
 ∙ repo                              https://github.com/openshift/os.git
 ∙ branch                            master
 ∙ variant                           scos
 ∙ version                           4.14
 ∙ rpm-artifacts-image               registry.ci.openshift.org/origin/4.14:artifacts
 ∙ target-registry                   quay.io/okd
 ∙ baseos-container-image-name       centos-stream-coreos-9
 ∙ extensions-container-image-name   centos-stream-coreos-9-extensions
 ∙ tag-latest                        false
 ∙ s3-bucket-name                    okd-scos
 ∙ s3-endpoint-url                   https://okd-scos.s3.amazonaws.com/
 ∙ matrix-room                       !nStsazaBvZCZQHPWTY:fedoraproject.org
 ∙ matrix-endpoint                   matrix.org

📂 Workspaces

 NAME                     SUB PATH   WORKSPACE BINDING
 ∙ registry-credentials   ---        Secret (secret=okd-scos-robot-pull-secret)
 ∙ s3-credentials         ---        Secret (secret=okd-scos-aws-config)
 ∙ shared-workspace       ---        PersistentVolumeClaim (claimName=pipeline-scos-next-pvc)

🗂  Taskruns

 NAME                                                              TASK NAME               STARTED          DURATION   STATUS
 ∙ okd-coreos-build-4.14-pipelinerun-k54sq-cosa-build-extensions   cosa-build-extensions   11 minutes ago   4m36s      Succeeded
 ∙ okd-coreos-build-4.14-pipelinerun-k54sq-cosa-buildextend        cosa-buildextend        11 minutes ago   10m22s     Succeeded
 ∙ okd-coreos-build-4.14-pipelinerun-k54sq-cosa-test               cosa-test               14 minutes ago   2m32s      Succeeded
 ∙ okd-coreos-build-4.14-pipelinerun-k54sq-cosa-build-baseos       cosa-build-baseos       24 minutes ago   10m43s     Succeeded
 ∙ okd-coreos-build-4.14-pipelinerun-k54sq-cosa-init               cosa-init               24 minutes ago   9s         Succeeded
 ∙ okd-coreos-build-4.14-pipelinerun-k54sq-rpm-artifacts-copy      rpm-artifacts-copy      25 minutes ago   8s        Succeeded
```

**Comment by aguidirh** [comment]
Verified 4.13 is working fine:

```
Name:              okd-coreos-build-4.13-pipelinerun-dqj5k
Namespace:         okd-team
Pipeline Ref:      okd-coreos-build
Service Account:   pipeline
Labels:
 tekton.dev/pipeline=okd-coreos-build
Annotations:
 chains.tekton.dev/signed=true
 operator.tekton.dev/prune.keep=1
 operator.tekton.dev/prune.resources=taskrun, pipelinerun
 operator.tekton.dev/prune.skip=false
 operator.tekton.dev/prune.strategy=keep

🌡️  Status

STARTED          DURATION   STATUS
25 minutes ago   24m36s     Succeeded

⏱  Timeouts
 Pipeline:   4h0m0s

⚓ Params

 NAME                                VALUE
 ∙ environment                       operate-first
 ∙ repo                              https://github.com/openshift/os.git
 ∙ branch                            master
 ∙ variant                           scos
 ∙ version                           4.13
 ∙ rpm-artifacts-image               registry.ci.openshift.org/origin/4.13:artifacts
 ∙ target-registry                   quay.io/okd
 ∙ baseos-container-image-name       centos-stream-coreos-9
 ∙ extensions-container-image-name   centos-stream-coreos-9-extensions
 ∙ tag-latest                        false
 ∙ s3-bucket-name                    okd-scos
 ∙ s3-endpoint-url                   https://okd-scos.s3.amazonaws.com/
 ∙ matrix-room                       !nStsazaBvZCZQHPWTY:fedoraproject.org
 ∙ matrix-endpoint                   matrix.org

📂 Workspaces

 NAME                     SUB PATH   WORKSPACE BINDING
 ∙ registry-credentials   ---        Secret (secret=okd-scos-robot-pull-secret)
 ∙ s3-credentials         ---        Secret (secret=okd-scos-aws-config)
 ∙ shared-workspace       ---        PersistentVolumeClaim (claimName=pipeline-scos-stable-pvc)

🗂  Taskruns

 NAME                                                              TASK NAME               STARTED          DURATION   STATUS
 ∙ okd-coreos-build-4.13-pipelinerun-dqj5k-cosa-build-extensions   cosa-build-extensions   11 minutes ago   4m39s      Succeeded
 ∙ okd-coreos-build-4.13-pipelinerun-dqj5k-cosa-buildextend        cosa-buildextend        11 minutes ago   10m27s     Succeeded
 ∙ okd-coreos-build-4.13-pipelinerun-dqj5k-cosa-test               cosa-test               14 minutes ago   3m39s      Succeeded
 ∙ okd-coreos-build-4.13-pipelinerun-dqj5k-cosa-build-baseos       cosa-build-baseos       25 minutes ago   10m10s     Succeeded
 ∙ okd-coreos-build-4.13-pipelinerun-dqj5k-cosa-init               cosa-init               25 minutes ago   9s         Succeeded
 ∙ okd-coreos-build-4.13-pipelinerun-dqj5k-rpm-artifacts-copy      rpm-artifacts-copy      25 minutes ago   8s         Succeeded
```

**Review by aguidirh — COMMENTED** [review]
Verified 4.14 and 4.13.

**Review by sherine-k — APPROVED** [review]
/approve
This has been tested with @aguidirh and @lmzuccarelli on the MOC cluster

**Pull request merged**
