### PR TITLE
Add a tekton pipeline building SCOS with COSA on knd

### PR DESCRIPTION
**Pull request by sherine-k**

### CODE REVIEW

**Review by lmzuccarelli — COMMENTED** [review]
Tested locally all working - kola basic test passing

**Comment by lmzuccarelli** [comment]
@sherine-k - I guess the real proof would be when we deploy on operate-first. So lets go ahead and merge we can always change as needed for operate first

**Comment by sherine-k** [comment]
Adds a tekton pipeline building SCOS with COSA on Kind

**Pull request merged**
